

server:
    port: 8080
    
spring:
    application:
        name: service-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enable: true
            
            routes:
                - id: employee
                  uri: http://localhost:8091
                  predicates:
                    -path=/api/employee/
                    
    