
server:
  port: 8092

spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-nttdata
    username: ENC(VquH1OZEI2kJanP78MAHW7qU3VlKqfgP)
    password: ENC(Dxko85RBJ9aePmhXQQl0vQofCQNj0hJ9)
 
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
  
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
