

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: employee
          uri: http://localhost:8091
          predicates:
            - Path=/api/employee/**
        - id: company
          uri: http://localhost:8095
          predicates:
            - Path=/api/company/**
