
server:
  port: 8092

spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-nttdata
    username: root
    password: mysql
 
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
  
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    