server:
  port: 8091

spring:
  application:
    name: service-employee
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-nttdata
    username: *****
    password: *****
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
