server:
  port: 8091

spring:
  application:
    name: service-employee
  datasource:
    url: jdbc:mysql://localhost:3306/microservice-nttdata
    username: ENC(ZNoH5grjfhnd7yrd6m/okBcqvB8bapLf)
    password: ENC(1oBvJTVaQobZP7LaVgZv+NWJVBU3WdrG)
jasypt:
  encryptor:
    password: Java2021
  
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
