

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: employee
          uri: lb://service-employee
          predicates:
            - Path=/api/employee/**
          filters:
           #- JwtAuthenticationFilter
           - StripPrefix=2
        - id: company
          uri: lb://servicio-auth
          predicates:
            - Path=/api/company/**
          predicates:
            - Path=/api/servicio-auth/**
          filters:
            - StripPrefix=2

#http://localhost:8095
